---
version: '3'
services:

  minecraft-server:
    container_name: minecraft
    environment:
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      DIFFICULTY: hard
      EULA: "TRUE"
      FORCE_GAMEMODE: "TRUE"
      MAX_PLAYERS: 5
      MOTD: Server by kurone-kito
      OPS: kuronekito
      PVP: "FALSE"
      SEED: ${SEED}
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    stdin_open: true
    restart: always
    tty: true
    volumes:
    - minecraft_data:/data

volumes:
  minecraft_data:
